<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\icon.ico</ApplicationIcon>
    <AssemblyName>Setup</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Assets\icon.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <SetupTemplateFile Include="..\Templates\RS.SetupApp.Template\product.json">
      <TargetPath>product.json</TargetPath>
    </SetupTemplateFile>
    <SetupTemplateFile Include="..\Templates\RS.SetupApp.Template\product.schema.json">
      <TargetPath>product.schema.json</TargetPath>
    </SetupTemplateFile>
    <SetupTemplateFile Include="..\Templates\RS.SetupApp.Template\LICENSE.txt">
      <TargetPath>LICENSE.txt</TargetPath>
    </SetupTemplateFile>
    <SetupTemplateFile Include="..\Templates\RS.SetupApp.Template\assets\**\*">
      <TargetPath>assets\%(RecursiveDir)%(Filename)%(Extension)</TargetPath>
    </SetupTemplateFile>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RS.SetupApp.Core\RS.SetupApp.Core.csproj" />
  </ItemGroup>

  <Target Name="CopySetupTemplateFiles" AfterTargets="Build">
    <Copy
      SourceFiles="@(SetupTemplateFile)"
      DestinationFiles="@(SetupTemplateFile->'$(OutDir)%(TargetPath)')"
      SkipUnchangedFiles="true" />
  </Target>

</Project>
