using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RS.Widgets.Enums
{
    public enum IconKey : int
    {
        Close = 1,
        Minus = 2,
        Maxsize = 3,
        Restore = 4,
        Question = 5,
        Message = 6,
        CustomerService = 7,
        More = 8,
        LineChart = 9,
        Swap = 10,
        WinSwap = 11,
        Ellipsis = 12,
        Plus = 13,
        Monitor = 14,
        MonitorMouseOver = 15,
        EyeShow = 16,
        EyeHide = 17,
        Lock = 18,
        UnLock = 19,
        UpTriangle = 20,
        LeftTriangle = 21,
        RightTriangle = 22,
        PK = 23,
        Edit = 24,
        Audience = 25,
        ThumbUp = 26,
        Gift = 27,
        Operate = 28,
        PopularityChart = 29,
        Checked = 30,
        HorizontalVerticalScreens = 31,
        EnvironmentDetection = 32,
        Speaker = 33,
        BeautyFilter = 34,
        Recorder = 35,
        LocalRecorder = 36,
        Setting = 37,
        Medal = 38,
        User = 39,
        Password = 40,
        Verify = 41,
        CheckMark = 42,
        Wrong = 43,
        DefaultLoadingIcon = 44,
        Error = 45,
        Hand = 46,
        Stop = 47,
        Question1 = 48,
        Exclamation = 49,
        Warning = 50,
        Asterisk = 51,
        Information = 52,
        Search = 53,
        Home = 54,
        SerialPort = 55,
        ModbusRTU = 56,
        ModbusTCP = 57,
        EmptyData = 58,
        Detect = 59,
        Segment = 60,
        Classify = 61,
        Pose = 62,
        OBB = 63,
        Img = 64,
        Folder = 65,
        CancelSelect = 66,
        Delete = 67,
        FullScreen = 68,
        LeftArrow = 69,
        RightArrow = 70,
        DownArrow = 71,
        UpArrow = 72,
        Add = 73,
        ScaleDown = 74,
        ScaleUp = 75,
        Location = 76,
        Return = 77,
        Email = 78,
        FirstPage = 79,
        EndPage = 80,
        BrowseBack = 81,
        BrowseForward = 82,
        Calendar = 83,
        Date = 84,
        TriangleUp = 85,
        TriangleDown = 86,
        TriangleLeft = 87,
        TriangleRight = 88
    }
}
